import { ExpoConfig } from '@expo/config';

const NAME = process.env.APP_NAME ?? 'TripTick';
const SLUG = process.env.SLUG ?? 'triptick';
const OWNER = process.env.OWNER ?? 'kozmickb';
const PROJECT_ID = process.env.PROJECT_ID ?? undefined; // Will be generated by eas init
const BUNDLE_ID = process.env.IOS_BUNDLE_ID ?? 'com.triptick.app';
const ANDROID_PACKAGE = process.env.ANDROID_PACKAGE ?? 'com.triptick.app';

const updatesUrl = "https://u.expo.dev/62ed6c16-c869-42cd-b91c-c82a9e410526";

const config: ExpoConfig = {
  name: NAME,
  slug: SLUG,
  owner: OWNER,
  scheme: 'triptick',
  version: '1.0.0',
  orientation: 'portrait',
  icon: './assets/TT logo.png',
  userInterfaceStyle: 'light',
  splash: {
    image: './assets/splash.png',
    resizeMode: 'contain',
    backgroundColor: '#FF6B6B'
  },
  assetBundlePatterns: [
    '**/*'
  ],
  ios: { 
    bundleIdentifier: BUNDLE_ID, 
    supportsTablet: true
  },
  // Android configuration removed - iOS only
  web: {
    favicon: './assets/favicon.png'
  },
  plugins: [
    'expo-font'
  ],
  experiments: {
    typedRoutes: true
  },
  extra: {
    eas: { projectId: "62ed6c16-c869-42cd-b91c-c82a9e410526" },
  },
  updates: { url: updatesUrl },
};

export default config;
