[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["cd server && npm ci"]

[phases.build]
cmds = ["cd server && npm run build"]

[start]
cmd = "chmod +x railway-start.sh && ./railway-start.sh"
