[build]
builder = "nixpacks"

[deploy]
startCommand = "chmod +x deploy.sh && ./deploy.sh"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[environments.production]
variables = { NODE_ENV = "production" }
