name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: server

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: server/package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Build TypeScript
      run: npm run build

    - name: Validate Prisma schema
      run: npx prisma validate --schema=./prisma/schema.prisma
      env:
        DATABASE_URL: "postgresql://user:password@localhost:5432/testdb"

    - name: Run tests (if available)
      run: npm test
      continue-on-error: true
